#!/usr/bin/python2.7
import sys, os, site

ver = sys.version[0:3]
path = site.getsitepackages()[0]

command = 'python%s %s/FloorplanMaker/FloorplanMaker.pyc '%(ver,path)
os.system(command+' '.join(sys.argv[1:]))
