# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Fri Aug 29 11:27:33 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from floorplanFrameBeh import FloorplanFrame
from heatersTable import HeatersTable
from thermometersTable import ThermometersTable
import FloorplanMakerIcons_rc
import os

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FloorplanMaker(object):
    def setupUi(self, FloorplanMaker):
        FloorplanMaker.setObjectName(_fromUtf8("FloorplanMaker"))
        FloorplanMaker.resize(1400,700)
        self.window = FloorplanMaker
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/usr/local/include/.icons/FloorplanMaker/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FloorplanMaker.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(FloorplanMaker)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.thermometers_list = []
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.heaterTabLab = QtGui.QLabel(self.centralwidget)
        self.heaterTabLab.setObjectName(_fromUtf8("heaterTabLab"))
        self.verticalLayout_3.addWidget(self.heaterTabLab)

        self.heaterTable = HeatersTable(self.centralwidget)

        item = QtGui.QTableWidgetItem()
        self.heaterTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.heaterTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.heaterTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.heaterTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddHeater = QtGui.QPushButton(self.centralwidget)
        self.btnAddHeater.setMaximumSize(QtCore.QSize(71, 27))
        self.btnAddHeater.setObjectName(_fromUtf8("btnAddHeater"))
        self.horizontalLayout.addWidget(self.btnAddHeater)
        self.btnModifyHeater = QtGui.QPushButton(self.centralwidget)
        self.btnModifyHeater.setMaximumSize(QtCore.QSize(91, 27))
        self.btnModifyHeater.setObjectName(_fromUtf8("btnModifyHeater"))
        self.horizontalLayout.addWidget(self.btnModifyHeater)
        self.btnDeleteHeater = QtGui.QPushButton(self.centralwidget)
        self.btnDeleteHeater.setMaximumSize(QtCore.QSize(81, 27))
        self.btnDeleteHeater.setObjectName(_fromUtf8("btnDeleteHeater"))
        self.horizontalLayout.addWidget(self.btnDeleteHeater)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)

        self.tableThermometers = ThermometersTable(self.centralwidget)
        self.verticalLayout_3.addWidget(self.tableThermometers)

        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAddTherm = QtGui.QPushButton(self.centralwidget)
        self.btnAddTherm.setMaximumSize(QtCore.QSize(81, 27))
        self.btnAddTherm.setObjectName(_fromUtf8("btnAddTherm"))
        self.horizontalLayout_2.addWidget(self.btnAddTherm)
        self.btnModifyTherm = QtGui.QPushButton(self.centralwidget)
        self.btnModifyTherm.setMaximumSize(QtCore.QSize(91, 27))
        self.btnModifyTherm.setObjectName(_fromUtf8("btnModifyTherm"))
        self.horizontalLayout_2.addWidget(self.btnModifyTherm)
        self.btnDelete = QtGui.QPushButton(self.centralwidget)
        self.btnDelete.setMaximumSize(QtCore.QSize(81, 27))
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(0, 20, 0, 20)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.thermsInRowEdit = QtGui.QLineEdit(self.centralwidget)
        self.thermsInRowEdit.setMaximumSize(QtCore.QSize(100, 50))
        self.thermsInRowEdit.setObjectName(_fromUtf8("thermsInRowEdit"))
        self.gridLayout.addWidget(self.thermsInRowEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_2.setText("Thermometers in row: ")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.columnsInRowEdit = QtGui.QLineEdit(self.centralwidget)
        self.columnsInRowEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.columnsInRowEdit.setObjectName(_fromUtf8("columnsInRowEdit"))
        self.gridLayout.addWidget(self.columnsInRowEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_3.setText("Thermometers in column: ")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.generateButton = QtGui.QPushButton(self.centralwidget)
        self.generateButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.generateButton.setObjectName(_fromUtf8("generateButton"))
        self.generateButton.setText("Generate")
        self.gridLayout.addWidget(self.generateButton, 2, 0, 1, 1)
        self.generateActionCombo = QtGui.QComboBox(self.centralwidget)
        self.generateActionCombo.setObjectName(_fromUtf8("generateActionCombo"))
        self.generateActionCombo.addItem(_fromUtf8("Linear"))
        self.generateActionCombo.addItem(_fromUtf8("Net"))
        self.gridLayout.addWidget(self.generateActionCombo, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 118, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.floorplanLab = QtGui.QLabel(self.centralwidget)
        self.floorplanLab.setObjectName(_fromUtf8("floorplanLab"))
        self.verticalLayout_4.addWidget(self.floorplanLab)
        self.floorplanScrollArea = QtGui.QScrollArea(self.centralwidget)
        self.floorplanScrollArea.setMinimumSize(QtCore.QSize(120, 160))
        self.floorplanScrollArea.setMaximumSize(QtCore.QSize(925, 16777215))
        self.floorplanScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.floorplanScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.floorplanScrollArea.setWidgetResizable(True)
        self.floorplanScrollArea.setObjectName(_fromUtf8("floorplanScrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 684, 701))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 681, 591))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.widget = QtGui.QWidget()
        self.widgetLayout = QtGui.QHBoxLayout()
        self.FrameFloorplan = QtGui.QFrame()
        self.FrameFloorplan.setMinimumSize(690,920)
        self.FloorPlanFrame = FloorplanFrame(self.FrameFloorplan, self)
        self.FloorPlanFrame.setMinimumSize(690,920)
        self.FloorPlanFrame.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
                                                    "border-radius: 4px;\n"
                                                    "padding: 2px;\n"
                                                    "background-color: rgb(194, 194, 194)\n"
                                                    ""))
        self.FloorPlanFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FloorPlanFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.FloorPlanFrame.setObjectName(_fromUtf8("FloorPlanFrame"))
        self.widgetLayout.addWidget(self.FrameFloorplan)
        self.widget.setLayout(self.widgetLayout)
        self.floorplanScrollArea.setWidget(self.widget)
        FloorplanMaker.setCentralWidget(self.centralwidget)
        self.verticalLayout_4.addWidget(self.floorplanScrollArea)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        FloorplanMaker.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FloorplanMaker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        self.menuNarz_dzia = QtGui.QMenu(self.menubar)
        self.menuNarz_dzia.setObjectName(_fromUtf8("menuNarz_dzia"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        FloorplanMaker.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FloorplanMaker)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        FloorplanMaker.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(FloorplanMaker)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        FloorplanMaker.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_project = QtGui.QAction(FloorplanMaker)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionSave_project = QtGui.QAction(FloorplanMaker)
        self.actionSave_project.setObjectName(_fromUtf8("actionSave_project"))
        self.actionClose = QtGui.QAction(FloorplanMaker)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionNewProject = QtGui.QAction(FloorplanMaker)
        self.actionNewProject.setObjectName(_fromUtf8("actionNewProject"))
        self.actionOpenProject = QtGui.QAction(FloorplanMaker)
        self.actionOpenProject.setObjectName(_fromUtf8("actionOpenProject"))
        self.actionSave = QtGui.QAction(FloorplanMaker)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionEnd = QtGui.QAction(FloorplanMaker)
        self.actionEnd.setObjectName(_fromUtf8("actionEnd"))
        self.actionGeneriloFile = QtGui.QAction(FloorplanMaker)
        self.actionGeneriloFile.setObjectName(_fromUtf8("actionGeneriloFile"))
        self.actionAbout = QtGui.QAction(FloorplanMaker)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionZoom_Floorplan = QtGui.QAction(FloorplanMaker)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("/usr/local/include/.icons/FloorplanMaker/magnifier_zoom_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Floorplan.setIcon(icon1)
        self.actionZoom_Floorplan.setObjectName(_fromUtf8("actionZoom_Floorplan"))
        self.actionZoom_out = QtGui.QAction(FloorplanMaker)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("/usr/local/include/.icons/FloorplanMaker/magnifier_zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon2)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.menuPlik.addAction(self.actionNewProject)
        self.menuPlik.addAction(self.actionOpenProject)
        self.menuPlik.addAction(self.actionSave)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionEnd)
        self.menuNarz_dzia.addAction(self.actionGeneriloFile)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuNarz_dzia.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionZoom_Floorplan)
        self.toolBar.addAction(self.actionZoom_out)

        self.retranslateUi(FloorplanMaker)
        QtCore.QObject.connect(self.actionEnd, QtCore.SIGNAL(_fromUtf8("triggered()")), FloorplanMaker.close)
        QtCore.QObject.connect(self.actionZoom_Floorplan, QtCore.SIGNAL(_fromUtf8("activated()")), self.FloorPlanFrame.zoomIn)
        QtCore.QObject.connect(self.actionZoom_out, QtCore.SIGNAL(_fromUtf8("activated()")), self.FloorPlanFrame.zoomOut)
        QtCore.QMetaObject.connectSlotsByName(FloorplanMaker)

    def retranslateUi(self, FloorplanMaker):
        FloorplanMaker.setWindowTitle(QtGui.QApplication.translate("FloorplanMaker", "FloorplanMaker", None, QtGui.QApplication.UnicodeUTF8))
        self.heaterTabLab.setText(QtGui.QApplication.translate("FloorplanMaker", "Placed heaters:", None, QtGui.QApplication.UnicodeUTF8))
        item = self.heaterTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("FloorplanMaker", "Color", None))
        item = self.heaterTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("FloorplanMaker", "Name", None))
        item = self.heaterTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("FloorplanMaker", "Type", None))
        self.btnAddHeater.setText(QtGui.QApplication.translate("FloorplanMaker", "Add", None))
        self.btnModifyHeater.setText(QtGui.QApplication.translate("FloorplanMaker", "Modify", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeleteHeater.setText(QtGui.QApplication.translate("FloorplanMaker", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FloorplanMaker", "Placed thermometers:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddTherm.setText(QtGui.QApplication.translate("FloorplanMaker", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnModifyTherm.setText(QtGui.QApplication.translate("FloorplanMaker", "Modify", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("FloorplanMaker", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.floorplanLab.setText(QtGui.QApplication.translate("FloorplanMaker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Project Floorplan:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlik.setTitle(QtGui.QApplication.translate("FloorplanMaker", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNarz_dzia.setTitle(QtGui.QApplication.translate("FloorplanMaker", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("FloorplanMaker", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_project.setText(QtGui.QApplication.translate("FloorplanMaker", "Otwórz projekt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_project.setText(QtGui.QApplication.translate("FloorplanMaker", "Zapisz projekt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("FloorplanMaker", "Zamknij", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewProject.setText(QtGui.QApplication.translate("FloorplanMaker", "New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setText(QtGui.QApplication.translate("FloorplanMaker", "Open project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("FloorplanMaker", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd.setText(QtGui.QApplication.translate("FloorplanMaker", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGeneriloFile.setText(QtGui.QApplication.translate("FloorplanMaker", "Create generilo file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("FloorplanMaker", "About", None))
        self.actionZoom_Floorplan.setText(QtGui.QApplication.translate("FloorplanMaker", "Zoom in", None))
        self.actionZoom_Floorplan.setShortcut(QtGui.QApplication.translate("FloorplanMaker", "Ctrl++", None))
        self.actionZoom_out.setText(QtGui.QApplication.translate("FloorplanMaker", "Zoom out", None))
        self.actionZoom_out.setToolTip(QtGui.QApplication.translate("FloorplanMaker", "Zoom out", None))
        self.actionZoom_out.setShortcut(QtGui.QApplication.translate("FloorplanMaker", "Ctrl+-", None))


